name: meter_readings
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3
  - ipykernel
  - pandas
  - numpy
  - seaborn
  - matplotlib
  - scipy
  - scikit-learn
  - openpyxl
  - xlrd
  - keras-gpu
  - tensorflow-gpu
  - pillow
  - exifread
  - pyzmq>=19
  - pip:
    - '--editable=.'
    - click
    - Sphinx
    - coverage
    - flake8
    - python-dotenv>=0.5.1
